# Generated by Django 4.2.11 on 2024-04-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_numreviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
